# Generated by Django 5.0.6 on 2025-03-09 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_child_day_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="day_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="personincustody",
            name="day_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="spouce",
            name="day_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
